use criterion::criterion_main;

mod benchmarks;
mod helper;

criterion_main! {
    // OHLCV benchmarks
    benchmarks::ohlcv::ad_bench::ohlcv,
    benchmarks::ohlcv::adosc_bench::ohlcv,
    benchmarks::ohlcv::adr_bench::ohlcv,
    benchmarks::ohlcv::adx_bench::ohlcv,
    benchmarks::ohlcv::adxr_bench::ohlcv,
    benchmarks::ohlcv::aroon_bench::ohlcv,
    benchmarks::ohlcv::aroonosc_bench::ohlcv,
    benchmarks::ohlcv::atr_bench::ohlcv,
    benchmarks::ohlcv::bbands_bench::ohlcv,
    benchmarks::ohlcv::bop_bench::ohlcv,
    benchmarks::ohlcv::cci_bench::ohlcv,
    benchmarks::ohlcv::cdl_doji_bench::ohlcv,
    benchmarks::ohlcv::cdl_dragonfly_doji_bench::ohlcv,
    benchmarks::ohlcv::cdl_gravestone_doji_bench::ohlcv,
    benchmarks::ohlcv::cdl_hammer_bench::ohlcv,
    benchmarks::ohlcv::cdl_inverted_hammer_bench::ohlcv,
    benchmarks::ohlcv::cdl_long_shadow_bench::ohlcv,
    benchmarks::ohlcv::cdl_marubozu_bench::ohlcv,
    benchmarks::ohlcv::dema_bench::ohlcv,
    benchmarks::ohlcv::dx_bench::ohlcv,
    benchmarks::ohlcv::ecl_bench::ohlcv,
    benchmarks::ohlcv::ema_bench::ohlcv,
    benchmarks::ohlcv::macd_bench::ohlcv,
    benchmarks::ohlcv::medprice_bench::ohlcv,
    benchmarks::ohlcv::mfi_bench::ohlcv,
    benchmarks::ohlcv::midpoint_bench::ohlcv,
    benchmarks::ohlcv::midprice_bench::ohlcv,
    benchmarks::ohlcv::minus_di_bench::ohlcv,
    benchmarks::ohlcv::minus_dm_bench::ohlcv,
    benchmarks::ohlcv::mom_bench::ohlcv,
    benchmarks::ohlcv::natr_bench::ohlcv,
    benchmarks::ohlcv::obv_bench::ohlcv,
    benchmarks::ohlcv::plus_di_bench::ohlcv,
    benchmarks::ohlcv::plus_dm_bench::ohlcv,
    benchmarks::ohlcv::rma_bench::ohlcv,
    benchmarks::ohlcv::roc_bench::ohlcv,
    benchmarks::ohlcv::rocp_bench::ohlcv,
    benchmarks::ohlcv::rocr_bench::ohlcv,
    benchmarks::ohlcv::rocr100_bench::ohlcv,
    benchmarks::ohlcv::rsi_bench::ohlcv,
    benchmarks::ohlcv::sar_bench::ohlcv,
    benchmarks::ohlcv::sma_bench::ohlcv,
    benchmarks::ohlcv::stoch_bench::ohlcv,
    benchmarks::ohlcv::supertrend_bench::ohlcv,
    benchmarks::ohlcv::t3_bench::ohlcv,
    benchmarks::ohlcv::tema_bench::ohlcv,
    benchmarks::ohlcv::trix_bench::ohlcv,
    benchmarks::ohlcv::trange_bench::ohlcv,
    benchmarks::ohlcv::trima_bench::ohlcv,
    benchmarks::ohlcv::trix_bench::ohlcv,
    benchmarks::ohlcv::typprice_bench::ohlcv,
    benchmarks::ohlcv::vegas_bench::ohlcv,
    benchmarks::ohlcv::wclprice_bench::ohlcv,
    benchmarks::ohlcv::willr_bench::ohlcv,
    benchmarks::ohlcv::wma_bench::ohlcv,
    benchmarks::ohlcv::vwap_bench::ohlcv,

    // Stats benchmarks
    benchmarks::stats::max_bench::stats,
    benchmarks::stats::min_bench::stats,
    benchmarks::stats::stddev_bench::stats,
    benchmarks::stats::sum_bench::stats,
    benchmarks::stats::var_bench::stats,

    // Helper benchmarks
    // benchmarks::helper::helper,
}
